@API_CINE_HostAddress = http://localhost:5266

GET {{API_CINE_HostAddress}}/api/tickets
Accept: application/json

###

GET {{API_CINE_HostAddress}}/api/tickets/2
Accept: application/json

###

GET {{API_CINE_HostAddress}}/api/tickets/99
Accept: application/json

###

POST {{API_CINE_HostAddress}}/api/tickets
Content-Type: application/json

{
  "clienteId": 1,
  "peliculaId": 2,
  "fechaFuncion": "2026-10-12T20:00:00",
  "sala": "Sala 3",
  "asiento": "D5",
  "precio": 22.00
}

###

PUT {{API_CINE_HostAddress}}/api/tickets/1
Content-Type: application/json

{
  "clienteId": 1,
  "peliculaId": 1,
  "fechaFuncion": "2026-10-10T18:00:00",
  "sala": "Sala 1",
  "asiento": "G8",
  "precio": 15.50
}

###

DELETE {{API_CINE_HostAddress}}/api/tickets/3

###

### ERROR 400: validaciones (asiento mal escrito y precio fuera de rango)
POST {{API_CINE_HostAddress}}/api/tickets
Content-Type: application/json

{
  "clienteId": 1,
  "peliculaId": 2,
  "fechaFuncion": "2026-10-12T20:00:00",
  "sala": "Sala 3",
  "asiento": "Z99",
  "precio": 100
}

### ERROR 409: asiento ya vendido (el ticket 2 ya tiene C4 en esa función)
POST {{API_CINE_HostAddress}}/api/tickets
Content-Type: application/json

{
  "clienteId": 1,
  "peliculaId": 2,
  "fechaFuncion": "2026-10-10T19:30:00",
  "sala": "Sala 3",
  "asiento": "C4",
  "precio": 22.00
}

### ERROR 400: la película no existe
POST {{API_CINE_HostAddress}}/api/tickets
Content-Type: application/json

{
  "clienteId": 1,
  "peliculaId": 99,
  "fechaFuncion": "2026-10-12T20:00:00",
  "sala": "Sala 3",
  "asiento": "D5",
  "precio": 22.00
}

###
